[Setting]
current_theme          = text
inject_theme_js        = 1
replace_colors         = 1
overwrite_assets       = 0
spotify_launch_flags   = 
always_enable_devtools = 0
color_scheme           = Spotify
inject_css             = 1
check_spicetify_update = 1
spotify_path           = /Applications/Spotify.app/Contents/Resources
prefs_path             = /Users/yashsharma/Library/Application Support/Spotify/prefs

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = marketplace|stats
sidebar_config        = 0

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.3.3.264.gdaf3b824
with    = 2.45.1
